<?php

$data = json_decode($data, true);

if(isset($_COOKIE['login'])) {
    echo "<a href='/login/logout/' class = 'btn btn-danger d-flex float-right'>Logout</a>";
}
else {
    echo "<h3>Not allowed to guest</h3>";
    die;
}
?>
<section style="background-color: #eee;">
  <div class="container py-5">

    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-4">

        <div class="card">
          <div class="card-header d-flex justify-content-between align-items-center p-3"
            style="border-top: 4px solid #ffa900;">
            <h5 class="mb-0">Chat messages</h5>
            <div class="d-flex flex-row align-items-center">
              <i class="fas fa-minus me-3 text-muted fa-xs"></i>
              <i class="fas fa-comments me-3 text-muted fa-xs"></i>
              <i class="fas fa-times text-muted fa-xs"></i>
            </div>
          </div>
          <div class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px">
<?php
 foreach ($data as $key => $value) {
    foreach ($value as $uid => $message) {
        if ($uid != $_COOKIE['login']) {
            echo "<div class='d-flex flex-row justify-content-start'>
            <img src='https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava5-bg.webp'
            alt='avatar 1' style='width: 45px; height: 100%;'>
            <div>
            <p class='small p-2 ms-3 mb-1 rounded-3 style=background-color: #f5f6f7;'>
                $message[msg]
            </p>
            <p class='small ms-3 mb-3 rounded-3 text-muted'>23:58</p>
            </div>
            </div>";
        } else {
            
            echo "<div class='d-flex flex-row justify-content-end mb-4 pt-1'>
            <div>
            <p class='small p-2 me-3 mb-1 text-white rounded-3 bg-primary'>
            $message[msg]
            </p>
            <p class='small me-3 mb-3 rounded-3 text-muted d-flex justify-content-end'>
            17:27
            </p>
            </div>
            <img src='https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava5-bg.webp'
            alt='avatar 1' style='width: 45px; height: 100%;'>
            
            </div>";
        }
    }
}
?>

          </div>
          <div class="card-footer text-muted d-flex justify-content-start align-items-center p-3">
            <form action="/chat/add/" method="post" >
            <div class="input-group mb-0">
              <input type="text" name="chat" class="form-control mx-1" placeholder="Type message"
                aria-label="Recipient's username" aria-describedby="button-addon2" />
               
              <button class="btn btn-warning mx-1" type="submit" id="button-addon2" style="padding-top: .55rem;">
                Send
              </button>
            </div>
            </form>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>